# This file contains values from Cookiecutter

default_context:
  project_name: "svaeva-evaluation"
  project_description: "`svaeva-evaluation` is a Python cli/package"
  organization: "svaeva-evaluation"
  license: "MIT"
  minimal_python_version: 3.11
  github_name: "elacosse"
  email: "eric@gradiente.space"
  version: "0.1.0"
  line_length: "120"
  create_example_template: "none"
